from collections.abc import Sequence
from typing import Protocol, runtime_checkable

import numpy as np


@runtime_checkable
class HandAdapter(Protocol):
    def init(self): ...
    def get_positions(self) -> Sequence[int]: ...
    def set_positions(self, positions: Sequence[int]): ...
    def get_tactile(self) -> np.ndarray: ...
    def reset(self): ...
    def stop(self): ...


class DummyDexHand:
    def __init__(self, dim=6):
        self.dim = dim

    def init(self): ...
    def get_positions(self) -> Sequence[int]:
        return [0] * self.dim

    def set_positions(self, positions: Sequence[int]): ...
    def reset(self): ...
    def stop(self): ...
